export const n4Part3 = [
    { kanji: '経済', meaning: 'economics, economy', romaji: 'keizai' },
    { kanji: '見物', meaning: 'sightseeing, watching', romaji: 'kenbutsu' },
    { kanji: '喧嘩', meaning: 'quarrel, brawl, fight', romaji: 'kenka' },
    { kanji: '研究', meaning: 'study, research, investigation', romaji: 'kenkyuu' },
    { kanji: '研究室', meaning: 'laboratory', romaji: 'kenkyuushitsu' },
    { kanji: '消しゴム', meaning: 'eraser', romaji: 'keshogomu' },
    { kanji: '景色', meaning: 'scenery, landscape', romaji: 'keshiki' },
    { kanji: '気', meaning: 'spirit, mind, heart', romaji: 'ki' },
    { kanji: '厳しい', meaning: 'severe, strict, rigid', romaji: 'kibishii' },
    { kanji: '気分', meaning: 'feeling, mood', romaji: 'kibun' },
    { kanji: '機会', meaning: 'chance, opportunity', romaji: 'kikai' },
    { kanji: '危険', meaning: 'danger, peril, hazard', romaji: 'kiken' },
    { kanji: '聞こえる', meaning: 'to be heard, to be audible', romaji: 'kikoeru' },
    { kanji: '決る', meaning: 'to be decided, to be settled', romaji: 'kimaru' },
    { kanji: '決める', meaning: 'to decide, to choose', romaji: 'kimeru' },
    { kanji: '君', meaning: 'you, buddy, pal', romaji: 'kimi' },
    { kanji: '気持ち', meaning: 'feeling, sensation, mood', romaji: 'kimochi' },
    { kanji: '近所', meaning: 'neighborhood', romaji: 'kinjo' },
    { kanji: '季節', meaning: 'season', romaji: 'kisetsu' },
    { kanji: '汽車', meaning: 'train', romaji: 'kisha' },
    { kanji: '規則', meaning: 'rule, regulation', romaji: 'kisoku' },
    { kanji: 'きっと', meaning: 'surely, undoubtedly', romaji: 'kitto' },
    { kanji: '心', meaning: 'mind, heart, spirit', romaji: 'kokoro' },
    { kanji: '国内', meaning: 'internal, domestic', romaji: 'kokunai' },
    { kanji: '国際', meaning: 'international', romaji: 'kokusai' },
    { kanji: '細かい', meaning: 'small, fine, minute', romaji: 'komakai' },
    { kanji: '米', meaning: 'rice', romaji: 'kome' },
    { kanji: '込む', meaning: 'to be crowded, to be packed', romaji: 'komu' },
    { kanji: '今度', meaning: 'this time, next time', romaji: 'kondo' },
    { kanji: 'この間', meaning: 'the other day, lately', romaji: 'kono aida' },
    { kanji: 'この頃', meaning: 'recently, nowadays', romaji: 'kono goro' },
    { kanji: '今夜', meaning: 'this evening, tonight', romaji: 'kon’ya' },
    { kanji: 'これから', meaning: 'after this', romaji: 'kore kara' },
    { kanji: '故障', meaning: 'breakdown, out of order', romaji: 'koshou' },
    { kanji: '答え', meaning: 'answer, reply, response', romaji: 'kotae' },
    { kanji: '事', meaning: 'thing, matter', romaji: 'koto' },
    { kanji: '小鳥', meaning: 'small bird, songbird', romaji: 'kotori' },
    { kanji: '校長', meaning: 'principal, headmaster', romaji: 'kouchou' },
    { kanji: '講堂', meaning: 'auditorium, lecture hall', romaji: 'koudou' },
    { kanji: '郊外', meaning: 'suburb, outskirts', romaji: 'kougai' },
    { kanji: '講義', meaning: 'lecture', romaji: 'kougi' },
    { kanji: '工業', meaning: '(manufacturing) industry', romaji: 'kougyou' },
    { kanji: '工場', meaning: 'factory, plant, mill', romaji: 'koujou' },
    { kanji: '高校', meaning: 'senior high school, high school', romaji: 'koukou' },
    { kanji: '高校生', meaning: 'senior high school student', romaji: 'koukousei' },
    { kanji: '公務員', meaning: 'government worker, public servant', romaji: 'koumuin' },
    { kanji: '交通', meaning: 'traffic, transportation', romaji: 'koutsuu' },
    { kanji: '壊れる', meaning: 'to be broken', romaji: 'kowareru' },
    { kanji: '壊す', meaning: 'to break, to destroy', romaji: 'kowasu' },
    { kanji: '首', meaning: 'neck', romaji: 'kubi' },
    { kanji: '雲', meaning: 'cloud', romaji: 'kumo' },
    { kanji: '比べる', meaning: 'to compare', romaji: 'kuraberu' },
    { kanji: '暮れる', meaning: 'to get dark, to grow dark', romaji: 'kureru' },
    { kanji: '草', meaning: 'grass, weed, herb', romaji: 'kusa' },
    { kanji: '空気', meaning: 'air, atmosphere', romaji: 'kuuki' },
    { kanji: '空港', meaning: 'airport', romaji: 'kuukou' },
    { kanji: '怖い', meaning: 'scary, frightening', romaji: 'kowai' },
    { kanji: '客', meaning: 'guest, visitor', romaji: 'kyaku' },
    { kanji: '教育', meaning: 'education, schooling', romaji: 'kyouiku' },
    { kanji: '教会', meaning: 'church', romaji: 'kyoukai' },
    { kanji: '興味', meaning: 'interest, curiosity', romaji: 'kyoumi' },
    { kanji: '競争', meaning: 'competition, contest', romaji: 'kyousou' },
    { kanji: '急', meaning: 'sudden, abrupt, unexpected', romaji: 'kyuu' },
    { kanji: '急行', meaning: 'moving at high speed', romaji: 'kyuukou' },
    { kanji: '間違える', meaning: 'to make a mistake', romaji: 'machigaeru' },
    { kanji: '参る', meaning: 'to go, to come (humble)', romaji: 'mairu' },
    { kanji: '真面目', meaning: 'seriousness, earnestness', romaji: 'majime' },
    { kanji: '負ける', meaning: 'to lose, to be defeated', romaji: 'makeru' },
    { kanji: '漫画', meaning: 'cartoon, comic', romaji: 'manga' },
    { kanji: '間に合う', meaning: 'to be in time for', romaji: 'maniau' },
    { kanji: '真中', meaning: 'middle, center', romaji: 'mannaka' },
    { kanji: 'または', meaning: 'or, otherwise', romaji: 'matawa' },
    { kanji: '周り', meaning: 'surroundings, neighbourhood', romaji: 'mawari' },
    { kanji: '回る', meaning: 'to turn, to revolve', romaji: 'mawaru' },
    { kanji: 'まず', meaning: 'first of all', romaji: 'mazu' },
    { kanji: '召し上がる', meaning: 'to eat, to drink', romaji: 'meshiagaru' },
    { kanji: '珍しい', meaning: 'unusual, rare, curious', romaji: 'mezurashii' },
    { kanji: '見える', meaning: 'to be seen, to be in sight', romaji: 'mieru' },
    { kanji: '港', meaning: 'harbor, port', romaji: 'minato' },
    { kanji: '見つかる', meaning: 'to be found', romaji: 'mitsukaru' },
    { kanji: '見つける', meaning: 'to discover, to find', romaji: 'mitsukeru' },
    { kanji: '湖', meaning: 'lake', romaji: 'mizuumi' },
    { kanji: 'もちろん', meaning: 'of course, certainly', romaji: 'mochiron' },
    { kanji: '戻る', meaning: 'to return, to go back', romaji: 'modoru' },
    { kanji: '森', meaning: 'forest', romaji: 'mori' },
    { kanji: 'もし', meaning: 'if, in case', romaji: 'moshi' },
    { kanji: '申し上げる', meaning: 'to say, to tell (humble)', romaji: 'moushiageru' },
    { kanji: '申す', meaning: 'to say, to be called (humble)', romaji: 'mousu' },
    { kanji: 'もうすぐ', meaning: 'soon, shortly', romaji: 'mousugu' },    
];