export const n4Part5 = [
    { kanji: '盛ん', meaning: 'popular, prosperous', romaji: 'sakan' },
    { kanji: 'さっき', meaning: 'some time ago, just now', romaji: 'sakki' },
    { kanji: '昨夜', meaning: 'last night', romaji: 'sakuya' },
    { kanji: '産業', meaning: 'industry', romaji: 'sangyou' },
    { kanji: 'さ来月', meaning: 'month after next', romaji: 'saraigetsu' },
    { kanji: 'さ来週', meaning: 'week after next', romaji: 'saraishuu' },
    { kanji: '差し上げる', meaning: 'to give, to offer', romaji: 'sashiageru' },
    { kanji: '騒ぐ', meaning: 'to make noise, to rustle', romaji: 'sawagu' },
    { kanji: '触る', meaning: 'to touch, to feel', romaji: 'sawaru' },
    { kanji: '政治', meaning: 'politics, government', romaji: 'seiji' },
    { kanji: '生活', meaning: 'living, life', romaji: 'seikatsu' },
    { kanji: '生産', meaning: 'production, manufacture', romaji: 'seisan' },
    { kanji: '西洋', meaning: 'the west, Western countries', romaji: 'seiyou' },
    { kanji: '世界', meaning: 'the world, society', romaji: 'sekai' },
    { kanji: '席', meaning: 'seat', romaji: 'seki' },
    { kanji: '線', meaning: 'line, stripe, stria', romaji: 'sen' },
    { kanji: '背中', meaning: 'back (of body)', romaji: 'senaka' },
    { kanji: '先輩', meaning: 'senior (at work or school)', romaji: 'senpai' },
    { kanji: '戦争', meaning: 'war', romaji: 'sensou' },
    { kanji: '説明', meaning: 'explanation, exposition', romaji: 'setsumei' },
    { kanji: '世話', meaning: 'looking after, help', romaji: 'sewa' },
    { kanji: '社長', meaning: 'company president', romaji: 'shachou' },
    { kanji: '社会', meaning: 'society, public, community', romaji: 'shakai' },
    { kanji: '市', meaning: 'city', romaji: 'shi' },
    { kanji: '試合', meaning: 'match, game', romaji: 'shiai' },
    { kanji: 'しばらく', meaning: 'little while, short while', romaji: 'shibaraku' },
    { kanji: '叱る', meaning: 'to scold', romaji: 'shikaru' },
    { kanji: '仕方', meaning: 'way, method, means', romaji: 'shikata' },
    { kanji: '試験', meaning: 'examination, exam, test', romaji: 'shiken' },
    { kanji: 'しっかり', meaning: 'tightly, firmly, securely', romaji: 'shikkari' },
    { kanji: '島', meaning: 'island', romaji: 'shima' },
    { kanji: '市民', meaning: 'citizen, citizenry, public', romaji: 'shimin' },
    { kanji: '品物', meaning: 'goods, article, thing', romaji: 'shinamono' },
    { kanji: '新聞社', meaning: 'newspaper company', romaji: 'shinbunsha' },
    { kanji: '心配', meaning: 'worry, concern, anxiety', romaji: 'shinpai' },
    { kanji: '親切', meaning: 'kindness, gentleness', romaji: 'shinsetsu' },
    { kanji: '調べる', meaning: 'to examine, to investigate', romaji: 'shiraberu' },
    { kanji: '知らせる', meaning: 'to notify, to advise, to inform', romaji: 'shiraseru' },
    { kanji: '下着', meaning: 'underwear', romaji: 'shitagi' },
    { kanji: '支度', meaning: 'preparation, arrangements', romaji: 'shitaku' },
    { kanji: '失礼', meaning: 'discourtesy, impoliteness', romaji: 'shitsurei' },
    { kanji: '失敗', meaning: 'failure, mistake, blunder', romaji: 'shippai' },
    { kanji: '食事', meaning: 'meal', romaji: 'shokuji' },
    { kanji: '食料品', meaning: 'foodstuff, groceries', romaji: 'shokuryouhin' },
    { kanji: '小学校', meaning: 'primary school', romaji: 'shougakkou' },
    { kanji: '紹介', meaning: 'introduction, presentation', romaji: 'shoukai' },
    { kanji: '小説', meaning: 'novel, (short) story', romaji: 'shousetsu' },
    { kanji: '将来', meaning: 'future, prospects', romaji: 'shourai' },
    { kanji: '招待', meaning: 'invitation', romaji: 'shoutai' },
    { kanji: '趣味', meaning: 'hobby, pastime', romaji: 'shumi' },
    { kanji: '出発', meaning: 'departure', romaji: 'shuppatsu' },
    { kanji: '出席', meaning: 'attendance, presence', romaji: 'shusseki' },
    { kanji: '習慣', meaning: 'habit, custom', romaji: 'shuukan' },
    { kanji: '祖母', meaning: 'grandmother', romaji: 'sobo' },
    { kanji: '育てる', meaning: 'to raise, to rear, to bring up', romaji: 'sodateru' },
    { kanji: '祖父', meaning: 'grandfather', romaji: 'sofu' },
    { kanji: 'そんな', meaning: 'such', romaji: 'sonna' },
    { kanji: 'それで', meaning: 'and, thereupon', romaji: 'sore de' },
    { kanji: 'それほど', meaning: 'to that degree', romaji: 'sore hodo' },
    { kanji: 'それに', meaning: 'besides, in addition', romaji: 'sore ni' },
    { kanji: 'そろそろ', meaning: 'soon, momentarily', romaji: 'sorosoro' },
    { kanji: '卒業', meaning: 'graduation', romaji: 'sotsugyou' },
    { kanji: '相談', meaning: 'consultation, discussion', romaji: 'soudan' },
    { kanji: '素晴らしい', meaning: 'wonderful, splendid', romaji: 'subarashii' },
    { kanji: '滑る', meaning: 'to glide, to slide', romaji: 'suberu' },
    { kanji: '水道', meaning: 'water supply, water service', romaji: 'suidou' },
    { kanji: '過ぎる', meaning: 'to pass through, to pass by', romaji: 'sugiru' },
    { kanji: '凄い', meaning: 'terrible, dreadful, amazing', romaji: 'sugoi' },
    { kanji: '水泳', meaning: 'swimming', romaji: 'suiei' },
    { kanji: 'すっかり', meaning: 'all, completely, totally', romaji: 'sukkari' },
    { kanji: '空く', meaning: 'to become empty', romaji: 'suku' },
    { kanji: '隅', meaning: 'corner, nook, recess', romaji: 'sumi' },
    { kanji: '済む', meaning: 'to finish, to end', romaji: 'sumu' },
    { kanji: '砂', meaning: 'sand, grit', romaji: 'suna' },
    { kanji: '進む', meaning: 'to advance, to go forward', romaji: 'susumu' },
    { kanji: '捨てる', meaning: 'to throw away, to cast away', romaji: 'suteru' },
    { kanji: '数学', meaning: 'mathematics', romaji: 'suugaku' },
    { kanji: '正しい', meaning: 'right, correct', romaji: 'tadashii' },
    { kanji: '退院', meaning: 'discharge from hospital', romaji: 'taiin' },
    { kanji: '大抵', meaning: 'mostly, ordinarily', romaji: 'taitei' },
    { kanji: 'たまに', meaning: 'occasionally, once in a while', romaji: 'tama ni' },
    { kanji: '棚', meaning: 'shelf, shelves', romaji: 'tana' },
    { kanji: '楽しみ', meaning: 'enjoyment, pleasure', romaji: 'tanoshimi' },
    { kanji: '楽む', meaning: 'to enjoy (oneself)', romaji: 'tanoshimu' },
    { kanji: '倒れる', meaning: 'to fall, to collapse', romaji: 'taoreru' },
    { kanji: '足りる', meaning: 'to be sufficient, to be enough', romaji: 'tariru' },
    { kanji: '確か', meaning: 'sure, certain, positive', romaji: 'tashika' },
    { kanji: '足す', meaning: 'to add, to top up', romaji: 'tasu' },
    { kanji: '多数', meaning: 'large number, many', romaji: 'tasuu' },    
];