export const n4Part6 = [
    { kanji: '畳', meaning: 'tatami mat', romaji: 'tatami' },
    { kanji: '立てる', meaning: 'to stand up', romaji: 'tateru' },
    { kanji: '建てる', meaning: 'to build, to construct', romaji: 'tateru' },
    { kanji: '訪ねる', meaning: 'to visit, to call on', romaji: 'tazuneru' },
    { kanji: '尋ねる', meaning: 'to ask, to enquire', romaji: 'tazuneru' },
    { kanji: '手袋', meaning: 'glove, mitten, mitt', romaji: 'tebukuro' },
    { kanji: '丁寧', meaning: 'polite, courteous, careful', romaji: 'teinei' },
    { kanji: '適当', meaning: 'suitable, proper, fit', romaji: 'tekitou' },
    { kanji: '点', meaning: 'point, dot, spot', romaji: 'ten' },
    { kanji: '天', meaning: 'sky', romaji: 'ten' },
    { kanji: '店員', meaning: 'shop assistant, clerk', romaji: 'ten’in' },
    { kanji: '天気予報', meaning: 'weather forecast', romaji: 'tenkiyohou' },
    { kanji: '展覧会', meaning: 'exhibition', romaji: 'tenrankai' },
    { kanji: '寺', meaning: 'temple (Buddhist)', romaji: 'tera' },
    { kanji: '手伝う', meaning: 'to help, to assist, to aid', romaji: 'tetsudau' },
    { kanji: '届ける', meaning: 'to deliver, to send', romaji: 'todokeru' },
    { kanji: '床屋', meaning: 'barbershop, barber', romaji: 'tokoya' },
    { kanji: '特別', meaning: 'special', romaji: 'tokubetsu' },
    { kanji: '特に', meaning: 'particularly, especially', romaji: 'toku ni' },
    { kanji: '特急', meaning: 'limited express', romaji: 'tokkyuu' },
    { kanji: '泊まる', meaning: 'to stay at (e.g. hotel)', romaji: 'tomaru' },
    { kanji: '遠く', meaning: 'far away, distant', romaji: 'tooku' },
    { kanji: '通る', meaning: 'to go by, to go past', romaji: 'tooru' },
    { kanji: '取り替える', meaning: 'to exchange, to replace', romaji: 'torikaeru' },
    { kanji: 'とうとう', meaning: 'finally, at', romaji: 'toutou' },
    { kanji: '都合', meaning: 'circumstances, convenience', romaji: 'tsugou' },
    { kanji: '捕まえる', meaning: 'to catch, to arrest', romaji: 'tsukamaeru' },
    { kanji: '月', meaning: 'moon', romaji: 'tsuki' },
    { kanji: '付く', meaning: 'to be attached, to adhere', romaji: 'tsuku' },
    { kanji: '妻', meaning: 'wife', romaji: 'tsuma' },
    { kanji: '連れる', meaning: 'to lead, to take (a person)', romaji: 'tsureru' },
    { kanji: '釣る', meaning: 'to fish, to lure in', romaji: 'tsuru' },
    { kanji: '伝える', meaning: 'to convey, to report', romaji: 'tsutaeru' },
    { kanji: '包む', meaning: 'to wrap up, to tuck in', romaji: 'tsutsumu' },
    { kanji: '続ける', meaning: 'to continue, to keep up', romaji: 'tsuzukeru' },
    { kanji: '続く', meaning: 'to continue, to last, to go on', romaji: 'tsuzuku' },
    { kanji: '腕', meaning: 'arm', romaji: 'ude' },
    { kanji: '植える', meaning: 'to plant, to grow, to raise', romaji: 'ueru' },
    { kanji: '動く', meaning: 'to move, to stir, to shift', romaji: 'ugoku' },
    { kanji: '受ける', meaning: 'to receive, to get', romaji: 'ukeru' },
    { kanji: '受付', meaning: 'reception (desk), information desk', romaji: 'uketsuke' },
    { kanji: '旨い', meaning: 'delicious, appetizing', romaji: 'umai' },
    { kanji: '運動', meaning: 'exercise, motion', romaji: 'undou' },
    { kanji: '運転', meaning: 'operation, operating', romaji: 'unten' },
    { kanji: '運転手', meaning: 'driver, chauffeur', romaji: 'untenshu' },
    { kanji: '裏', meaning: 'reverse side, rear, back', romaji: 'ura' },
    { kanji: '嬉しい', meaning: 'happy, glad', romaji: 'ureshii' },
    { kanji: '売り場', meaning: 'sales floor, counter (in shop)', romaji: 'uriba' },
    { kanji: '嘘', meaning: 'lie, falsehood', romaji: 'uso' },
    { kanji: '打つ', meaning: 'to hit, to strike, to knock', romaji: 'utsu' },
    { kanji: '美しい', meaning: 'beautiful, lovely', romaji: 'utsukushii' },
    { kanji: '移る', meaning: 'to move (house), to transfer (department)', romaji: 'utsuru' },
    { kanji: '写す', meaning: 'to transcribe, to duplicate', romaji: 'utsusu' },
    { kanji: '別れる', meaning: 'to part, to separate', romaji: 'wakareru' },
    { kanji: '沸かす', meaning: 'to boil, to heat', romaji: 'wakasu' },
    { kanji: '訳', meaning: 'reason, cause', romaji: 'wake' },
    { kanji: '沸く', meaning: 'to grow hot, to boil', romaji: 'waku' },
    { kanji: '笑う', meaning: 'to laugh', romaji: 'warau' },
    { kanji: '割れる', meaning: 'to break, to be smashed', romaji: 'wareru' },
    { kanji: '割合', meaning: 'rate, ratio', romaji: 'wariai' },
    { kanji: '忘れ物', meaning: 'something forgotten', romaji: 'wasuremono' },
    { kanji: 'やはり', meaning: 'as expected', romaji: 'yahari' },
    { kanji: '焼ける', meaning: 'to be roasted', romaji: 'yakeru' },
    { kanji: '焼く', meaning: 'to burn, to roast, to bake', romaji: 'yaku' },
    { kanji: '役に立つ', meaning: 'to be helpful, to be useful', romaji: 'yaku ni tatsu' },
    { kanji: '約束', meaning: 'promise, agreement', romaji: 'yakusoku' },
    { kanji: '止める', meaning: 'to stop', romaji: 'yameru' },
    { kanji: '止む', meaning: 'to cease, to stop', romaji: 'yamu' },
    { kanji: '優しい', meaning: 'tender, kind, gentle', romaji: 'yasashii' },
    { kanji: '痩せる', meaning: 'to become thin, to slim', romaji: 'yaseru' },
    { kanji: 'やっと', meaning: 'at last', romaji: 'yatto' },
    { kanji: '柔らかい', meaning: 'soft, tender', romaji: 'yawarakai' },
    { kanji: '用', meaning: 'business, task, errand', romaji: 'you' },
    { kanji: '汚れる', meaning: 'to get dirty', romaji: 'yogoreru' },
    { kanji: '喜ぶ', meaning: 'to be delighted', romaji: 'yorokobu' },
    { kanji: '寄る', meaning: 'to approach, to drop by', romaji: 'yoru' },
    { kanji: '予習', meaning: 'preparation for a lesson', romaji: 'yoshuu' },
    { kanji: '予定', meaning: 'plans, arrangement', romaji: 'yotei' },
    { kanji: '用意', meaning: 'preparation, arrangements', romaji: 'youi' },
    { kanji: '用事', meaning: 'tasks, things to do', romaji: 'youji' },
    { kanji: '予約', meaning: 'reservation, appointment', romaji: 'yoyaku' },
    { kanji: '湯', meaning: 'hot water', romaji: 'yu' },
    { kanji: '指', meaning: 'finger, toe', romaji: 'yubi' },
    { kanji: '指輪', meaning: '(finger) ring', romaji: 'yubiwa' },
    { kanji: '夢', meaning: 'dream', romaji: 'yume' },
    { kanji: '輸入', meaning: 'import, importation', romaji: 'yunyuu' },
    { kanji: '揺れる', meaning: 'to shake, to sway', romaji: 'yureru' },
    { kanji: '輸出', meaning: 'export', romaji: 'yushutsu' },
    { kanji: '夕食', meaning: 'evening meal, dinner', romaji: 'yuushoku' },
    { kanji: '残念', meaning: 'deplorable, regret, bad luck', romaji: 'zannen' },
    { kanji: '随分', meaning: 'very, extremely, surprisingly', romaji: 'zuibun' },    
];