export const n4Part1 = [
    { kanji: '上がる', meaning: 'to rise, to ascend', romaji: 'agaru' },
    { kanji: '挨拶', meaning: 'greeting, salutation', romaji: 'aisatsu' },
    { kanji: '味', meaning: 'flavor, taste', romaji: 'aji' },
    { kanji: '赤ちゃん', meaning: 'baby, infant', romaji: 'akachan' },
    { kanji: '赤ん坊', meaning: 'baby, infant', romaji: 'akanbou' },
    { kanji: '案内', meaning: 'guidance, leading (the way)', romaji: 'annai' },
    { kanji: '安心', meaning: 'relief, peace of mind', romaji: 'anshin' },
    { kanji: '安全', meaning: 'safety', romaji: 'anzen' },
    { kanji: '浅い', meaning: 'shallow, superficial', romaji: 'asai' },
    { kanji: '足音', meaning: 'sound of footsteps', romaji: 'ashioto' },
    { kanji: '遊び', meaning: 'playing', romaji: 'asobi' },
    { kanji: '集る', meaning: 'to gather, to collect, to assemble', romaji: 'atsumaru' },
    { kanji: '集める', meaning: 'to collect, to assemble, to gather', romaji: 'atsumeru' },
    { kanji: '合う', meaning: 'to fit, to match, to suit', romaji: 'au' },
    { kanji: '謝る', meaning: 'to apologize', romaji: 'ayamaru' },
    { kanji: '倍', meaning: 'twice, double, times', romaji: 'bai' },
    { kanji: '番組', meaning: 'program (e.g. TV)', romaji: 'bangumi' },
    { kanji: '場所', meaning: 'place, location', romaji: 'basho' },
    { kanji: '別', meaning: 'different, another', romaji: 'betsu' },
    { kanji: '美術館', meaning: 'art gallery, art museum', romaji: 'bijutsukan' },
    { kanji: 'びっくり', meaning: 'to be surprised', romaji: 'bikkuri' },
    { kanji: '僕', meaning: 'I, me', romaji: 'boku' },
    { kanji: '貿易', meaning: 'trade (foreign)', romaji: 'boueki' },
    { kanji: '部長', meaning: 'head of a section or department', romaji: 'buchou' },
    { kanji: 'ぶどう', meaning: 'grape', romaji: 'budou' },
    { kanji: '文学', meaning: 'literature', romaji: 'bungaku' },
    { kanji: '文化', meaning: 'culture, civilization', romaji: 'bunka' },
    { kanji: '文法', meaning: 'grammar', romaji: 'bunpou' },
    { kanji: '血', meaning: 'blood', romaji: 'chi' },
    { kanji: '力', meaning: 'force, strength, vigor', romaji: 'chikara' },
    { kanji: '地理', meaning: 'geography', romaji: 'chiri' },
    { kanji: '中学校', meaning: 'junior high school', romaji: 'chuugakkou' },
    { kanji: '注意', meaning: 'caution, being careful', romaji: 'chuui' },
    { kanji: '注射', meaning: 'injection', romaji: 'chuusha' },
    { kanji: '駐車場', meaning: 'parking lot', romaji: 'chuushajou' },
    { kanji: '大分', meaning: 'considerably, greatly', romaji: 'daibu' },
    { kanji: '大学生', meaning: 'university student', romaji: 'daigakusei' },
    { kanji: '大事', meaning: 'important, serious, crucial', romaji: 'daiji' },
    { kanji: '大体', meaning: 'general, substantially', romaji: 'daitai' },
    { kanji: 'だから', meaning: 'so, therefore', romaji: 'dakara' },
    { kanji: '駄目', meaning: 'no good, useless', romaji: 'dame' },
    { kanji: '暖房', meaning: '(indoor) heating', romaji: 'danbou' },
    { kanji: '男性', meaning: 'man, male', romaji: 'dansei' },
    { kanji: '電報', meaning: 'telegram', romaji: 'denpou' },
    { kanji: '電灯', meaning: 'electric light', romaji: 'dentou' },
    { kanji: 'どんどん', meaning: 'rapidly, continuously', romaji: 'dondon' },
    { kanji: '泥棒', meaning: 'thief, burglar, robber, theft', romaji: 'dorobou' },
    { kanji: '動物園', meaning: 'zoo', romaji: 'doubutsuen' },
    { kanji: '道具', meaning: 'tool, implement', romaji: 'dougu' },
    { kanji: '枝', meaning: 'branch, bough', romaji: 'eda' },
    { kanji: '遠慮', meaning: 'constraint, restraint, modesty', romaji: 'enryo' },
    { kanji: '選ぶ', meaning: 'to choose, to select', romaji: 'erabu' },
    { kanji: '不便', meaning: 'inconvenience', romaji: 'fuben' },
    { kanji: '増える', meaning: 'to increase, to multiply', romaji: 'fueru' },
    { kanji: '深い', meaning: 'deep, profound', romaji: 'fukai' },
    { kanji: '復習', meaning: 'review, revision', romaji: 'fukushuu' },
    { kanji: '複雑', meaning: 'complex, complicated', romaji: 'fukuzatsu' },
    { kanji: '踏む', meaning: 'to step on, to tread on', romaji: 'fumu' },
    { kanji: '船', meaning: 'ship, boat', romaji: 'fune' },
    { kanji: '布団', meaning: 'futon', romaji: 'futon' },
    { kanji: '太る', meaning: 'to grow fat', romaji: 'futoru' },
    { kanji: '普通', meaning: 'general, ordinary, usual', romaji: 'futsuu' },
    { kanji: '頑張る', meaning: 'to hang on, to do one’s best', romaji: 'ganbaru' },
    { kanji: '原因', meaning: 'cause, origin, source', romaji: 'gen’in' },
    { kanji: '下宿', meaning: 'boarding, lodging', romaji: 'geshuku' },
    { kanji: '技術', meaning: 'technology, engineering', romaji: 'gijutsu' },
    { kanji: 'ご馳走', meaning: 'feast, treating (someone)', romaji: 'gochisou' },
    { kanji: '塵', meaning: 'rubbish, trash, garbage', romaji: 'gomi' },
    { kanji: 'ご覧になる', meaning: 'to see, to look, to watch', romaji: 'goran ni naru' },
    { kanji: 'ご存じ', meaning: 'knowing', romaji: 'gozonji' },
    { kanji: 'ご主人', meaning: 'your husband', romaji: 'goshujin' },
    { kanji: '具合', meaning: 'condition, state, health', romaji: 'guai' },
    { kanji: '軍人', meaning: 'military personnel, soldier', romaji: 'gunjin' },
    { kanji: '葉', meaning: 'leaf', romaji: 'ha' },
    { kanji: '拝見', meaning: 'seeing, look at', romaji: 'haiken' },
    { kanji: '歯医者', meaning: 'dentist', romaji: 'haisha' },
    { kanji: '始める', meaning: 'to start, to begin', romaji: 'hajimeru' },
    { kanji: 'はっきり', meaning: 'clearly, plainly', romaji: 'hakkiri' },
    { kanji: '運ぶ', meaning: 'to carry, to transport', romaji: 'hakobu' },
    { kanji: '花見', meaning: 'cherry blossom viewing', romaji: 'hanami' },
    { kanji: '反対', meaning: 'opposition, resistance', romaji: 'hantai' },
    { kanji: '払う', meaning: 'to pay', romaji: 'harau' },
    { kanji: '発音', meaning: 'pronunciation', romaji: 'hatsuon' },
    { kanji: '林', meaning: 'woods, forest', romaji: 'hayashi' },
    { kanji: '恥ずかしい', meaning: 'shy, embarrassed', romaji: 'hazukashii' },
    { kanji: '変', meaning: 'strange, odd, peculiar', romaji: 'hen' },
    { kanji: '返事', meaning: 'reply, answer, response', romaji: 'henji' },
    { kanji: '酷い', meaning: 'cruel, heartless', romaji: 'hidoi' },
    { kanji: '冷える', meaning: 'to grow cold', romaji: 'hieru' },    
  ];