export const n4Part2 = [
    { kanji: 'ひげ', meaning: 'mustache, beard', romaji: 'hige' },
    { kanji: '非常に', meaning: 'very, extremely', romaji: 'hijou ni' },
    { kanji: '光', meaning: 'light, beam', romaji: 'hikari' },
    { kanji: '光る', meaning: 'to shine, to glitter', romaji: 'hikaru' },
    { kanji: '引き出し', meaning: 'drawer', romaji: 'hikidashi' },
    { kanji: '引き出す', meaning: 'to pull out, to take out', romaji: 'hikidasu' },
    { kanji: '引っ越す', meaning: 'to move (house)', romaji: 'hikkosu' },
    { kanji: '飛行場', meaning: 'airfield, airport', romaji: 'hikoujou' },
    { kanji: '開く', meaning: 'to open, to undo', romaji: 'hiraku' },
    { kanji: '昼間', meaning: 'daytime, during the day', romaji: 'hiruma' },
    { kanji: '拾う', meaning: 'to pick up', romaji: 'hirou' },
    { kanji: '昼休み', meaning: 'lunch break', romaji: 'hiruyasumi' },
    { kanji: '久しぶり', meaning: 'it’s been a while', romaji: 'hisashiburi' },
    { kanji: '褒める', meaning: 'to praise, to admire', romaji: 'homeru' },
    { kanji: '翻訳', meaning: 'translation', romaji: 'honyaku' },
    { kanji: '星', meaning: 'star', romaji: 'hoshi' },
    { kanji: 'ほとんど', meaning: 'mostly, nearly', romaji: 'hotondo' },
    { kanji: '法律', meaning: 'law', romaji: 'houritsu' },
    { kanji: '一度', meaning: 'once, one time', romaji: 'ichido' },
    { kanji: '医学', meaning: 'medical science, medicine', romaji: 'igaku' },
    { kanji: '苛める', meaning: 'to bully, to torment', romaji: 'ijimeru' },
    { kanji: '以上', meaning: 'not less than, beyond', romaji: 'ijou' },
    { kanji: '以下', meaning: 'not exceeding, below', romaji: 'ika' },
    { kanji: '意見', meaning: 'opinion, view, comment', romaji: 'iken' },
    { kanji: '生きる', meaning: 'to live, to exist', romaji: 'ikiru' },
    { kanji: '以内', meaning: 'within, inside of', romaji: 'inai' },
    { kanji: '田舎', meaning: 'rural area, countryside', romaji: 'inaka' },
    { kanji: '祈る', meaning: 'to pray, to wish', romaji: 'inoru' },
    { kanji: '一杯', meaning: 'full, a lot', romaji: 'ippai' },
    { kanji: '石', meaning: 'stone, gem, jewel', romaji: 'ishi' },
    { kanji: '一生懸命', meaning: 'very hard, with utmost effort', romaji: 'isshoukenmei' },
    { kanji: '急ぐ', meaning: 'to hurry, to rush', romaji: 'isogu' },
    { kanji: '糸', meaning: 'thread, yarn, string', romaji: 'ito' },
    { kanji: '邪魔', meaning: 'hindrance, obstacle', romaji: 'jama' },
    { kanji: '字', meaning: 'character (i.e. kanji)', romaji: 'ji' },
    { kanji: '時代', meaning: 'period, epoch, era, age', romaji: 'jidai' },
    { kanji: '事故', meaning: 'accident, incident, trouble', romaji: 'jiko' },
    { kanji: '事務所', meaning: 'office', romaji: 'jimusho' },
    { kanji: '神社', meaning: 'Shinto shrine', romaji: 'jinja' },
    { kanji: '人口', meaning: 'population', romaji: 'jinkou' },
    { kanji: '地震', meaning: 'earthquake', romaji: 'jishin' },
    { kanji: '辞典', meaning: 'dictionary', romaji: 'jiten' },
    { kanji: '自由', meaning: 'freedom, liberty', romaji: 'jiyuu' },
    { kanji: '女性', meaning: 'woman, female', romaji: 'josei' },
    { kanji: '準備', meaning: 'preparation, set up', romaji: 'junbi' },
    { kanji: '十分', meaning: 'plenty, enough, sufficient', romaji: 'juubun' },
    { kanji: '住所', meaning: 'address', romaji: 'juusho' },
    { kanji: '壁', meaning: 'wall, partition', romaji: 'kabe' },
    { kanji: '課長', meaning: 'section manager, section chief', romaji: 'kachou' },
    { kanji: '帰り', meaning: 'return, coming back', romaji: 'kaeri' },
    { kanji: '変える', meaning: 'to change, to alter', romaji: 'kaeru' },
    { kanji: '科学', meaning: 'science', romaji: 'kagaku' },
    { kanji: '鏡', meaning: 'mirror, looking-glass', romaji: 'kagami' },
    { kanji: '海岸', meaning: 'coast, beach', romaji: 'kaigan' },
    { kanji: '会議', meaning: 'meeting, conference', romaji: 'kaigi' },
    { kanji: '会議室', meaning: 'conference room', romaji: 'kaigishitsu' },
    { kanji: '会場', meaning: 'assembly hall, meeting place', romaji: 'kaijou' },
    { kanji: '会話', meaning: 'conversation', romaji: 'kaiwa' },
    { kanji: '火事', meaning: 'fire, conflagration', romaji: 'kaji' },
    { kanji: '掛ける', meaning: 'to hang, to hoist, to raise', romaji: 'kakeru' },
    { kanji: '格好', meaning: 'shape, form, figure', romaji: 'kakkou' },
    { kanji: '構う', meaning: 'to mind, to care about', romaji: 'kamau' },
    { kanji: '髪', meaning: 'hair (on the head)', romaji: 'kami' },
    { kanji: '噛む', meaning: 'to bite, to chew, to gnaw', romaji: 'kamu' },
    { kanji: '家内', meaning: '(my) wife', romaji: 'kanai' },
    { kanji: '必ず', meaning: 'always, without exception', romaji: 'kanarazu' },
    { kanji: '悲しい', meaning: 'sad, sorrowful', romaji: 'kanashii' },
    { kanji: '金持ち', meaning: 'rich person', romaji: 'kanemochi' },
    { kanji: '考える', meaning: 'to think about', romaji: 'kangaeru' },
    { kanji: '関係', meaning: 'relation, relationship, connection', romaji: 'kankei' },
    { kanji: '彼女', meaning: 'she, her', romaji: 'kanojo' },
    { kanji: '簡単', meaning: 'simple, easy, uncomplicated', romaji: 'kantan' },
    { kanji: '顔', meaning: 'face, look', romaji: 'kao' },
    { kanji: '彼', meaning: 'he, him', romaji: 'kare' },
    { kanji: '彼ら', meaning: 'they, them', romaji: 'karera' },
    { kanji: '形', meaning: 'form, shape, figure', romaji: 'katachi' },
    { kanji: '硬い', meaning: 'hard, solid, tough', romaji: 'katai' },
    { kanji: '片付ける', meaning: 'to tidy up, to put in order', romaji: 'katazukeru' },
    { kanji: '勝つ', meaning: 'to win, to gain victory', romaji: 'katsu' },
    { kanji: '乾く', meaning: 'to get dry', romaji: 'kawaku' },
    { kanji: '代わり', meaning: 'substitute, replacement', romaji: 'kawari' },
    { kanji: '変わる', meaning: 'to change, to be transformed', romaji: 'kawaru' },
    { kanji: '通う', meaning: 'to go back and forth between', romaji: 'kayou' },
    { kanji: '飾る', meaning: 'to decorate, to ornament', romaji: 'kazaru' },
    { kanji: '毛', meaning: 'hair, fur, wool', romaji: 'ke' },
    { kanji: '怪我', meaning: 'injury, hurt', romaji: 'kega' },
    { kanji: '計画', meaning: 'plan, project', romaji: 'keikaku' },
    { kanji: '経験', meaning: 'experience', romaji: 'keiken' },
    { kanji: '警察', meaning: 'police', romaji: 'keisatsu' },    
  ];