export const n4Part4 = [
    { kanji: '迎える', meaning: 'to go out to meet', romaji: 'mukaeru' },
    { kanji: '向かう', meaning: 'to face, to go towards', romaji: 'mukau' },
    { kanji: '昔', meaning: 'olden days, former', romaji: 'mukashi' },
    { kanji: '無理', meaning: 'unreasonable, impossible', romaji: 'muri' },
    { kanji: '虫', meaning: 'insect, bug', romaji: 'mushi' },
    { kanji: '息子', meaning: 'son', romaji: 'musuko' },
    { kanji: '娘', meaning: '(my) daughter, girl', romaji: 'musume' },
    { kanji: '投げる', meaning: 'to throw, to cast away', romaji: 'nageru' },
    { kanji: '中々', meaning: 'very, considerably', romaji: 'nakanaka' },
    { kanji: '泣く', meaning: 'to cry, to weep', romaji: 'naku' },
    { kanji: '無くなる', meaning: 'to be lost, to be missing', romaji: 'nakunaru' },
    { kanji: '亡くなる', meaning: 'to die', romaji: 'nakunaru' },
    { kanji: '治る', meaning: 'to be cured', romaji: 'naoru' },
    { kanji: '直る', meaning: 'to get mended', romaji: 'naoru' },
    { kanji: '直す', meaning: 'to fix, to repair', romaji: 'naosu' },
    { kanji: '慣れる', meaning: 'to get used to', romaji: 'nareru' },
    { kanji: '鳴る', meaning: 'to sound, to ring', romaji: 'naru' },
    { kanji: 'なるほど', meaning: 'I see!, That’s right!', romaji: 'naru hodo' },
    { kanji: '寝坊', meaning: 'sleeping in late', romaji: 'nebou' },
    { kanji: '値段', meaning: 'price, cost', romaji: 'nedan' },
    { kanji: '眠い', meaning: 'sleepy, drowsy', romaji: 'nemui' },
    { kanji: '眠る', meaning: 'to sleep', romaji: 'nemuru' },
    { kanji: '熱心', meaning: 'zeal, enthusiasm', romaji: 'nesshin' },
    { kanji: '熱', meaning: 'heat', romaji: 'netsu' },
    { kanji: '苦い', meaning: 'bitter', romaji: 'nigai' },
    { kanji: '逃げる', meaning: 'to escape, to run away', romaji: 'nigeru' },
    { kanji: '二階建て', meaning: 'two-storied building', romaji: 'nikaidate' },
    { kanji: '日記', meaning: 'diary, journal', romaji: 'nikki' },
    { kanji: '人形', meaning: 'doll', romaji: 'ningyou' },
    { kanji: '匂い', meaning: 'scent, smell', romaji: 'nioi' },
    { kanji: '似る', meaning: 'to resemble, to look like', romaji: 'niru' },
    { kanji: '喉', meaning: 'throat', romaji: 'nodo' },
    { kanji: '残る', meaning: 'to remain, to be left', romaji: 'nokoru' },
    { kanji: '乗り換える', meaning: 'to transfer (trains), to change (bus, train)', romaji: 'norikaeru' },
    { kanji: '乗り物', meaning: 'vehicle, conveyance', romaji: 'norimono' },
    { kanji: '濡れる', meaning: 'to get wet', romaji: 'nureru' },
    { kanji: '塗る', meaning: 'to paint, to plaster', romaji: 'nuru' },
    { kanji: '盗む', meaning: 'to steal', romaji: 'nusumu' },
    { kanji: '入学', meaning: 'entry to school or university', romaji: 'nyuugaku' },
    { kanji: '入院', meaning: 'hospitalization', romaji: 'nyuuin' },
    { kanji: '落ちる', meaning: 'to fall down, to drop', romaji: 'ochiru' },
    { kanji: '踊り', meaning: 'dance', romaji: 'odori' },
    { kanji: '驚く', meaning: 'to be surprised, to be astonished', romaji: 'odoroku' },
    { kanji: '踊る', meaning: 'to dance', romaji: 'odoru' },
    { kanji: 'お祝い', meaning: 'congratulations, celebration', romaji: 'oiwai' },
    { kanji: 'お嬢さん', meaning: '(your) daughter, young lady', romaji: 'ojousan' },
    { kanji: '可笑しい', meaning: 'funny, strange, odd', romaji: 'okashii' },
    { kanji: '行う', meaning: 'to perform, to do', romaji: 'okonau' },
    { kanji: '怒る', meaning: 'to get angry, to get mad', romaji: 'okoru' },
    { kanji: '起こす', meaning: 'to raise, to wake, to cause', romaji: 'okosu' },
    { kanji: '億', meaning: 'hundred million', romaji: 'oku' },
    { kanji: '屋上', meaning: 'rooftop', romaji: 'okujou' },
    { kanji: '贈り物', meaning: 'present, gift', romaji: 'okurimono' },
    { kanji: '遅れる', meaning: 'to be late, to be delayed', romaji: 'okureru' },
    { kanji: '送る', meaning: 'to send, to dispatch', romaji: 'okuru' },
    { kanji: 'お祭り', meaning: 'festival, feast, carnival', romaji: 'omatsuri' },
    { kanji: 'お見舞い', meaning: 'calling on someone who is ill', romaji: 'omimai' },
    { kanji: 'お土産', meaning: 'present, souvenir', romaji: 'omiyage' },
    { kanji: '玩具', meaning: 'toy, plaything', romaji: 'omocha' },
    { kanji: '思い出す', meaning: 'to recall, to remember', romaji: 'omoidasu' },
    { kanji: '表', meaning: 'surface, face, front, outside', romaji: 'omote' },
    { kanji: '思う', meaning: 'to think, to consider', romaji: 'omou' },
    { kanji: 'お礼', meaning: 'thanks, gratitude', romaji: 'orei' },
    { kanji: '折れる', meaning: 'to break, to be broken', romaji: 'oreru' },
    { kanji: '折る', meaning: 'to break, to fracture', romaji: 'oru' },
    { kanji: '押し入れ', meaning: 'closet', romaji: 'oshiire' },
    { kanji: '仰る', meaning: 'to say, to speak', romaji: 'ossharu' },
    { kanji: 'お宅', meaning: 'your house, your home, your family', romaji: 'otaku' },
    { kanji: '音', meaning: 'sound, noise', romaji: 'oto' },
    { kanji: '落とす', meaning: 'to drop, to let fall', romaji: 'otosu' },
    { kanji: '夫', meaning: 'husband', romaji: 'otto' },
    { kanji: 'お釣り', meaning: 'change (for a purchase)', romaji: 'otsuri' },
    { kanji: '終わり', meaning: 'the end', romaji: 'owari' },
    { kanji: '親', meaning: 'parent, parents', romaji: 'oya' },
    { kanji: '歴史', meaning: 'history', romaji: 'rekishi' },
    { kanji: '連絡', meaning: 'to contact, to get in touch', romaji: 'renraku' },
    { kanji: '利用', meaning: 'use, utilization', romaji: 'riyou' },
    { kanji: '理由', meaning: 'reason, motive', romaji: 'riyuu' },
    { kanji: '留守', meaning: 'absence, being away from home', romaji: 'rusu' },
    { kanji: '旅館', meaning: 'Japanese-style lodging', romaji: 'ryokan' },
    { kanji: '両方', meaning: 'both, both sides', romaji: 'ryouhou' },
    { kanji: '寂しい', meaning: 'lonely, lonesome, solitary', romaji: 'sabishii' },
    { kanji: '下がる', meaning: 'to come down, to get lower', romaji: 'sagaru' },
    { kanji: '探す', meaning: 'to search, to look for', romaji: 'sagasu' },
    { kanji: '下げる', meaning: 'to hang, to lower', romaji: 'sageru' },
    { kanji: '最後', meaning: 'last, final, latest', romaji: 'saigo' },
    { kanji: '最近', meaning: 'most recent, these days', romaji: 'saikin' },
    { kanji: '最初', meaning: 'beginning, first', romaji: 'saisho' },
    { kanji: '坂', meaning: 'slope, hill', romaji: 'saka' },    
];