export const n5Part6 = [
    { kanji: '掃除', meaning: 'cleaning, sweeping', romaji: 'souji' },
    { kanji: 'すぐ', meaning: 'immediately', romaji: 'sugu' },
    { kanji: '水曜日', meaning: 'Wednesday', romaji: 'suiyoubi' },
    { kanji: '好き', meaning: 'liking, fondness, love', romaji: 'suki' },
    { kanji: '少し', meaning: 'small quantity, little', romaji: 'sukoshi' },
    { kanji: '少ない', meaning: 'few, a little', romaji: 'sukunai' },
    { kanji: '住む', meaning: 'to live, to reside', romaji: 'sumu' },
    { kanji: 'する', meaning: 'to do', romaji: 'suru' },
    { kanji: '吸う', meaning: 'to smoke, to breathe in', romaji: 'suu' },
    { kanji: '座る', meaning: 'to sit', romaji: 'suwaru' },
    { kanji: '涼しい', meaning: 'cool, refreshing', romaji: 'suzushii' },
    { kanji: '煙草', meaning: 'tobacco, cigarette', romaji: 'tabako' },
    { kanji: '食べ物', meaning: 'food', romaji: 'tabemono' },
    { kanji: '食べる', meaning: 'to eat', romaji: 'taberu' },
    { kanji: '多分', meaning: 'perhaps, probably', romaji: 'tabun' },
    { kanji: '大変', meaning: 'very, greatly, immense', romaji: 'taihen' },
    { kanji: '大切', meaning: 'important, necessary', romaji: 'taisetsu' },
    { kanji: '大使館', meaning: 'embassy', romaji: 'taishikan' },
    { kanji: '高い', meaning: 'high, tall, expensive', romaji: 'takai' },
    { kanji: '沢山', meaning: 'a lot, plenty, many', romaji: 'takusan' },
    { kanji: '卵', meaning: 'egg, spawn', romaji: 'tamago' },
    { kanji: '誕生日', meaning: 'birthday', romaji: 'tanjoubi' },
    { kanji: '楽しい', meaning: 'enjoyable, fun', romaji: 'tanoshii' },
    { kanji: '頼む', meaning: 'to request, to beg, to ask', romaji: 'tanomu' },
    { kanji: '建物', meaning: 'building', romaji: 'tatemono' },
    { kanji: '立つ', meaning: 'to stand, to rise', romaji: 'tatsu' },
    { kanji: '手', meaning: 'hand', romaji: 'te' },
    { kanji: '手紙', meaning: 'letter', romaji: 'tegami' },
    { kanji: '天気', meaning: 'weather', romaji: 'tenki' },
    { kanji: '戸', meaning: 'door', romaji: 'to' },
    { kanji: '飛ぶ', meaning: 'to fly', romaji: 'tobu' },
    { kanji: '友達', meaning: 'friend, companion', romaji: 'tomodachi' },
    { kanji: '止まる', meaning: 'to stop (moving)', romaji: 'tomaru' },
    { kanji: '隣', meaning: 'neighbor, next to', romaji: 'tonari' },
    { kanji: '十日', meaning: 'tenth day of the month, ten days', romaji: 'tooka' },
    { kanji: '鳥', meaning: 'bird', romaji: 'tori' },
    { kanji: '取る', meaning: 'to take, to pick up', romaji: 'toru' },
    { kanji: '年', meaning: 'year, age', romaji: 'toshi' },
    { kanji: '図書館', meaning: 'library', romaji: 'toshokan' },
    { kanji: '時計', meaning: 'watch, clock', romaji: 'tokei' },
    { kanji: '時々', meaning: 'sometimes, at times', romaji: 'tokidoki' },
    { kanji: '所', meaning: 'place, spot, scene', romaji: 'tokoro' },
    { kanji: '遠い', meaning: 'far, distant', romaji: 'tooi' },
    { kanji: '撮る', meaning: 'to take (a photo), to record (a video)', romaji: 'toru' },
    { kanji: 'とても', meaning: 'very, exceedingly', romaji: 'totemo' },
    { kanji: '疲れる', meaning: 'to get tired', romaji: 'tsukareru' },
    { kanji: '次', meaning: 'next, following', romaji: 'tsugi' },
    { kanji: '使う', meaning: 'to use, to make use of', romaji: 'tsukau' },
    { kanji: '一日', meaning: 'first day of the month', romaji: 'tsuitachi' },
    { kanji: '着く', meaning: 'to arrive at, to reach', romaji: 'tsuku' },
    { kanji: '机', meaning: 'desk', romaji: 'tsukue' },
    { kanji: '作る', meaning: 'to make, to produce', romaji: 'tsukuru' },
    { kanji: '詰まらない', meaning: 'dull, uninteresting', romaji: 'tsumaranai' },
    { kanji: '冷たい', meaning: 'cold (to the touch)', romaji: 'tsumetai' },
    { kanji: '勤める', meaning: 'to work (for), to be employed (at)', romaji: 'tsutomeru' },
    { kanji: '強い', meaning: 'strong, powerful', romaji: 'tsuyoi' },
    { kanji: '上', meaning: 'above, up, over', romaji: 'ue' },
    { kanji: '生まれる', meaning: 'to be born', romaji: 'umareru' },
    { kanji: '海', meaning: 'sea, ocean', romaji: 'umi' },
    { kanji: '売る', meaning: 'to sell', romaji: 'uru' },
    { kanji: '煩い', meaning: 'noisy, loud', romaji: 'urusai' },
    { kanji: '後ろ', meaning: 'back, behind, rear', romaji: 'ushiro' },
    { kanji: '薄い', meaning: 'thin, pale, light', romaji: 'usui' },
    { kanji: '歌', meaning: 'song', romaji: 'uta' },
    { kanji: '歌う', meaning: 'to sing', romaji: 'utau' },
    { kanji: '上着', meaning: 'coat, jacket', romaji: 'uwagi' },
    { kanji: '若い', meaning: 'young, youthful', romaji: 'wakai' },
    { kanji: '分かる', meaning: 'to understand, to comprehend', romaji: 'wakaru' },
    { kanji: '悪い', meaning: 'bad, poor, inferior', romaji: 'warui' },
    { kanji: '忘れる', meaning: 'to forget', romaji: 'wasureru' },
    { kanji: '私', meaning: 'I, me', romaji: 'watashi' },
    { kanji: '渡る', meaning: 'to cross over', romaji: 'wataru' },
    { kanji: '渡す', meaning: 'to hand over, to hand in', romaji: 'watasu' },
    { kanji: '山', meaning: 'mountain', romaji: 'yama' },
    { kanji: 'やる', meaning: 'to do', romaji: 'yaru' },
    { kanji: '野菜', meaning: 'vegetable', romaji: 'yasai' },
    { kanji: '安い', meaning: 'cheap, inexpensive', romaji: 'yasui' },
    { kanji: '休み', meaning: 'rest, recess', romaji: 'yasumi' },
    { kanji: '休む', meaning: 'to be absent, to take a day off', romaji: 'yasumu' },
    { kanji: '呼ぶ', meaning: 'to call out, to call', romaji: 'yobu' },
    { kanji: '四日', meaning: 'fourth day of the month, four days', romaji: 'yokka' },
    { kanji: '横', meaning: 'horizontal', romaji: 'yoko' },
    { kanji: '読む', meaning: 'to read', romaji: 'yomu' },
    { kanji: '夜', meaning: 'evening, night', romaji: 'yoru' },
    { kanji: '洋服', meaning: 'Western-style clothes', romaji: 'youfuku' },
    { kanji: '八日', meaning: 'eight day of the month, eight days', romaji: 'youka' },
    { kanji: '弱い', meaning: 'weak, frail, delicate', romaji: 'yowai' },
    { kanji: '雪', meaning: 'snow', romaji: 'yuki' },
    { kanji: 'ゆっくり', meaning: 'slowly, at ease', romaji: 'yukkuri' },
    { kanji: '郵便局', meaning: 'post office', romaji: 'yuubinkyoku' },
    { kanji: '有名', meaning: 'famous', romaji: 'yuumei' },
    { kanji: '雑誌', meaning: 'journal, magazine', romaji: 'zasshi' },
    { kanji: '全部', meaning: 'all, entire, whole', romaji: 'zenbu' },
  ];