export const n5Part4 = [
    { kanji: '交番', meaning: 'police box', romaji: 'kouban' },
    { kanji: '紅茶', meaning: 'black tea', romaji: 'koucha' },
    { kanji: '公園', meaning: '(public) park', romaji: 'kouen' },
    { kanji: '子供', meaning: 'child, children', romaji: 'kodomo' },
    { kanji: '答える', meaning: 'to answer, to reply', romaji: 'kotaeru' },
    { kanji: '言葉', meaning: 'language, dialect', romaji: 'kotoba' },
    { kanji: '今年', meaning: 'this year', romaji: 'kotoshi' },
    { kanji: '交差点', meaning: 'crossing, intersection', romaji: 'kousaten' },
    { kanji: '聞く', meaning: 'to hear, to listen', romaji: 'kiku' },
    { kanji: '奇麗', meaning: 'pretty, lovely, beautiful', romaji: 'kirei' },
    { kanji: '去年', meaning: 'last year', romaji: 'kyonen' },
    { kanji: '今日', meaning: 'today, this day', romaji: 'kyou' },
    { kanji: '兄弟', meaning: 'siblings, brothers and sisters', romaji: 'kyoudai' },
    { kanji: '教室', meaning: 'classroom, department', romaji: 'kyoushitsu' },
    { kanji: '口', meaning: 'mouth, opening, hole', romaji: 'kuchi' },
    { kanji: '果物', meaning: 'fruit', romaji: 'kudamono' },
    { kanji: '曇り', meaning: 'cloudiness, cloudy weather', romaji: 'kumori' },
    { kanji: '国', meaning: 'country, state, region', romaji: 'kuni' },
    { kanji: '暗い', meaning: 'dark, gloomy', romaji: 'kurai' },
    { kanji: '黒い', meaning: 'black, dark', romaji: 'kuroi' },
    { kanji: '来る', meaning: 'to come', romaji: 'kuru' },
    { kanji: '車', meaning: 'car, automobile', romaji: 'kuruma' },
    { kanji: '薬', meaning: 'medicine', romaji: 'kusuri' },
    { kanji: '靴', meaning: 'shoes, boots', romaji: 'kutsu' },
    { kanji: '靴下', meaning: 'socks', romaji: 'kutsushita' },
    { kanji: '町', meaning: 'town, block', romaji: 'machi' },
    { kanji: 'まだ', meaning: 'still, not yet', romaji: 'mada' },
    { kanji: '前', meaning: 'front, ahead, previous', romaji: 'mae' },
    { kanji: '毎朝', meaning: 'every morning', romaji: 'maiasa' },
    { kanji: '毎晩', meaning: 'every night', romaji: 'maiban' },
    { kanji: '毎月', meaning: 'every month', romaji: 'maitsuki' },
    { kanji: '毎日', meaning: 'every day', romaji: 'mainichi' },
    { kanji: '毎週', meaning: 'every week', romaji: 'maishuu' },
    { kanji: '毎年', meaning: 'every year, yearly', romaji: 'maitoshi' },
    { kanji: '窓', meaning: 'window', romaji: 'mado' },
    { kanji: '曲がる', meaning: 'to bend, to curve', romaji: 'magaru' },
    { kanji: '万', meaning: 'ten thousand', romaji: 'man' },
    { kanji: '丸い', meaning: 'round, circular', romaji: 'marui' },
    { kanji: 'また', meaning: 'again, also', romaji: 'mata' },
    { kanji: '待つ', meaning: 'to wait, to look forward to', romaji: 'matsu' },
    { kanji: '不味い', meaning: 'unappetizing, unsavory', romaji: 'mazui' },
    { kanji: '目', meaning: 'eye, eyeball', romaji: 'me' },
    { kanji: '眼鏡', meaning: 'spectacles, glasses', romaji: 'megane' },
    { kanji: '道', meaning: 'road, street, way', romaji: 'michi' },
    { kanji: '緑', meaning: 'green', romaji: 'midori' },
    { kanji: '磨く', meaning: 'to polish, to shine', romaji: 'migaku' },
    { kanji: '右', meaning: 'right, right hand side', romaji: 'migi' },
    { kanji: '短い', meaning: 'short', romaji: 'mijikai' },
    { kanji: '耳', meaning: 'ear', romaji: 'mimi' },
    { kanji: '南', meaning: 'south', romaji: 'minami' },
    { kanji: '皆', meaning: 'all, everyone', romaji: 'minna' },
    { kanji: '見る', meaning: 'to see, to look, to watch', romaji: 'miru' },
    { kanji: '店', meaning: 'store, shop', romaji: 'mise' },
    { kanji: '見せる', meaning: 'to show, to display', romaji: 'miseru' },
    { kanji: '水', meaning: 'water', romaji: 'mizu' },
    { kanji: '門', meaning: 'gate', romaji: 'mon' },
    { kanji: '問題', meaning: 'question, problem', romaji: 'mondai' },
    { kanji: '持つ', meaning: 'to hold (in one’s hands)', romaji: 'motsu' },
    { kanji: '木曜日', meaning: 'Thursday', romaji: 'mokuyoubi' },
    { kanji: '六日', meaning: 'sixth day of the month, six days', romaji: 'muika' },
    { kanji: '向こう', meaning: 'opposite side, other side', romaji: 'mukou' },
    { kanji: '村', meaning: 'village', romaji: 'mura' },
    { kanji: '難しい', meaning: 'difficult, hard', romaji: 'muzukashii' },
    { kanji: '長い', meaning: 'long, lengthy', romaji: 'nagai' },
    { kanji: '中', meaning: 'inside, in, among', romaji: 'naka' },
    { kanji: '鳴く', meaning: 'to sing (bird)', romaji: 'naku' },
    { kanji: '無くす', meaning: 'to lose something', romaji: 'nakusu' },
    { kanji: '名前', meaning: 'name, full name', romaji: 'namae' },
    { kanji: '何', meaning: 'what', romaji: 'nani' },
    { kanji: '七日', meaning: 'seventh day of the month, seven days', romaji: 'nanoka' },
    { kanji: '並ぶ', meaning: 'to stand in a line', romaji: 'narabu' },
    { kanji: '並べる', meaning: 'to line up', romaji: 'naraberu' },
    { kanji: '習う', meaning: 'to be taught, to learn (from a teacher)', romaji: 'narau' },
    { kanji: 'なる', meaning: 'to become', romaji: 'naru' },
    { kanji: '夏', meaning: 'summer', romaji: 'natsu' },
    { kanji: '猫', meaning: 'cat', romaji: 'neko' },
    { kanji: '寝る', meaning: 'to go to bed', romaji: 'neru' },
    { kanji: '二', meaning: 'two', romaji: 'ni' },
    { kanji: '日曜日', meaning: 'Sunday', romaji: 'nichiyoubi' },
    { kanji: '賑やか', meaning: 'bustling, busy, lively', romaji: 'nigiyaka' },
    { kanji: '肉', meaning: 'flesh, meat', romaji: 'niku' },
    { kanji: '荷物', meaning: 'luggage, baggage', romaji: 'nimotsu' },
    { kanji: '西', meaning: 'west', romaji: 'nishi' },
    { kanji: '庭', meaning: 'garden, yard', romaji: 'niwa' },
    { kanji: '登る', meaning: 'to ascend, to go up', romaji: 'noboru' },
    { kanji: '飲物', meaning: 'drink, beverage', romaji: 'nomimono' },
    { kanji: '飲む', meaning: 'to drink, to gulp', romaji: 'nomu' },
    { kanji: '乗る', meaning: 'to get on (train, plane, bus, ship)', romaji: 'noru' },
    { kanji: '脱ぐ', meaning: 'to take off (clothes, shoes)', romaji: 'nugu' },
    { kanji: '伯母さん', meaning: 'aunt', romaji: 'obasan' },
    { kanji: 'お祖母さん', meaning: 'grandmother', romaji: 'obaasan' },
    { kanji: 'お弁当', meaning: 'Japanese lunch box', romaji: 'obentou' },    
  ];