export const n5Part1 = [
    { kanji: 'アパート', meaning: 'apartment', romaji: 'apaato' },
    { kanji: 'バス', meaning: 'bus', romaji: 'basu' },
    { kanji: 'ベッド', meaning: 'bed', romaji: 'beddo' },
    { kanji: 'デパート', meaning: 'department store', romaji: 'depaato' },
    { kanji: 'ドア', meaning: 'door (Western style)', romaji: 'doa' },
    { kanji: 'エレベータ', meaning: 'elevator', romaji: 'erebeeta' },
    { kanji: 'フォーク', meaning: 'fork', romaji: 'fooku' },
    { kanji: 'ギター', meaning: 'guitar', romaji: 'gitaa' },
    { kanji: 'グラム', meaning: 'gram', romaji: 'guramu' },
    { kanji: 'ホテル', meaning: 'hotel', romaji: 'hoteru' },
    { kanji: 'カメラ', meaning: 'camera', romaji: 'kamera' },
    { kanji: 'キロ', meaning: 'kilogram', romaji: 'kiro' },
    { kanji: 'コーヒー', meaning: 'coffee', romaji: 'koohii' },
    { kanji: 'コート', meaning: 'coat', romaji: 'kooto' },
    { kanji: 'コップ', meaning: 'glass', romaji: 'koppu' },
    { kanji: 'クラス', meaning: 'class', romaji: 'kurasu' },
    { kanji: 'パーティー', meaning: 'party', romaji: 'paatii' },
    { kanji: 'ペン', meaning: 'pen', romaji: 'pen' },
    { kanji: 'ペット', meaning: 'pet', romaji: 'petto' },
    { kanji: 'ポケット', meaning: 'pocket', romaji: 'poketto' },
    { kanji: 'プール', meaning: 'swimming pool', romaji: 'puuru' },
    { kanji: 'セーター', meaning: 'sweater, jumper', romaji: 'seetaa' },
    { kanji: 'シャワー', meaning: 'shower', romaji: 'shawaa' },
    { kanji: 'シャツ', meaning: 'shirt', romaji: 'shatsu' },
    { kanji: 'スカート', meaning: 'skirt', romaji: 'sukaato' },
    { kanji: 'スポーツ', meaning: 'sport', romaji: 'supootsu' },
    { kanji: 'スプーン', meaning: 'spoon', romaji: 'supuun' },
    { kanji: 'スリッパ', meaning: 'slippers', romaji: 'surippa' },
    { kanji: 'ストーブ', meaning: 'heater, stove', romaji: 'sutoobu' },
    { kanji: 'タクシー', meaning: 'taxi', romaji: 'takushii' },
    { kanji: 'テーブル', meaning: 'table', romaji: 'teeburu' },
    { kanji: 'テープ', meaning: 'tape', romaji: 'teepu' },
    { kanji: 'テープレコーダー', meaning: 'tape recorder', romaji: 'teepu rekoodaa' },
    { kanji: 'テレビ', meaning: 'television, TV', romaji: 'terebi' },
    { kanji: 'テスト', meaning: 'test', romaji: 'tesuto' },
    { kanji: 'トイレ', meaning: 'toilet, restroom', romaji: 'toire' },
    { kanji: 'ゼロ', meaning: 'zero, naught', romaji: 'zero' },
    { kanji: 'ズボン', meaning: 'trousers, pants', romaji: 'zubon' },
    { kanji: '浴びる', meaning: 'to take a shower', romaji: 'abiru' },
    { kanji: '危ない', meaning: 'dangerous, risky', romaji: 'abunai' },
    { kanji: 'あげる', meaning: 'to give', romaji: 'ageru' },
    { kanji: '赤い', meaning: 'red', romaji: 'akai' },
    { kanji: '明るい', meaning: 'bright, colorful', romaji: 'akarui' },
    { kanji: '開ける', meaning: 'to open', romaji: 'akeru' },
    { kanji: '秋', meaning: 'autumn', romaji: 'aki' },
    { kanji: '開く', meaning: 'to open', romaji: 'aku' },
    { kanji: '甘い', meaning: 'sweet', romaji: 'amai' },
    { kanji: '雨', meaning: 'rain', romaji: 'ame' },
    { kanji: 'あなた', meaning: 'you', romaji: 'anata' },
    { kanji: '兄', meaning: 'older brother', romaji: 'ani' },
    { kanji: '姉', meaning: 'older sister', romaji: 'ane' },
    { kanji: '青い', meaning: 'blue', romaji: 'aoi' },
    { kanji: '洗う', meaning: 'to wash', romaji: 'arau' },
    { kanji: '有る', meaning: 'to be, to exist', romaji: 'aru' },
    { kanji: '歩く', meaning: 'to walk', romaji: 'aruku' },
    { kanji: '朝', meaning: 'morning', romaji: 'asa' },
    { kanji: '朝ご飯', meaning: 'breakfast', romaji: 'asagohan' },
    { kanji: '明後日', meaning: 'day after tomorrow', romaji: 'asatte' },
    { kanji: '足', meaning: 'foot, leg', romaji: 'ashi' },
    { kanji: '明日', meaning: 'tomorrow', romaji: 'ashita' },
    { kanji: '遊ぶ', meaning: 'to play', romaji: 'asobu' },
    { kanji: 'あそこ', meaning: 'there, over there', romaji: 'asoko' },
    { kanji: '頭', meaning: 'head', romaji: 'atama' },
    { kanji: '暖かい', meaning: 'warm, mild', romaji: 'atatakai' },
    { kanji: '新しい', meaning: 'new, fresh', romaji: 'atarashii' },
    { kanji: '後', meaning: 'behind after, later', romaji: 'ato' },
    { kanji: '暑い', meaning: 'hot (weather)', romaji: 'atsui' },
    { kanji: '熱い', meaning: 'hot (thing)', romaji: 'atsui' },
    { kanji: '厚い', meaning: 'thick', romaji: 'atsui' },
    { kanji: '会う', meaning: 'to meet', romaji: 'au' },
    { kanji: '晩ご飯', meaning: 'dinner', romaji: 'bangohan' },
    { kanji: '番号', meaning: 'number', romaji: 'bangou' },
    { kanji: '勉強', meaning: 'study, diligence', romaji: 'benkyou' },
    { kanji: '便利', meaning: 'convenient, handy', romaji: 'benri' },
    { kanji: '帽子', meaning: 'hat, cap', romaji: 'boushi' },
    { kanji: '病院', meaning: 'hospital', romaji: 'byouin' },
    { kanji: '病気', meaning: 'illness, disease', romaji: 'byouki' },
    { kanji: '豚肉', meaning: 'pork', romaji: 'butaniku' },
    { kanji: '茶色', meaning: 'light brown', romaji: 'chairo' },
    { kanji: '茶碗', meaning: 'rice bowl, tea cup', romaji: 'chawan' },
    { kanji: '父', meaning: 'father', romaji: 'chichi' },
    { kanji: '違う', meaning: 'to differ (from)', romaji: 'chigau' },
    { kanji: '小さい', meaning: 'small, little, tiny', romaji: 'chiisai' },
    { kanji: '近い', meaning: 'near, close', romaji: 'chikai' },
    { kanji: '近く', meaning: 'near, neighborhood', romaji: 'chikaku' },
    { kanji: '地下鉄', meaning: 'subway, metro', romaji: 'chikatetsu' },
    { kanji: 'ちょっと', meaning: 'a little', romaji: 'chotto' },
    { kanji: 'ちょうど', meaning: 'exactly, precisely, just', romaji: 'choudo' },
    { kanji: '地図', meaning: 'map', romaji: 'chizu' },
    { kanji: '台所', meaning: 'kitchen', romaji: 'daidokoro' },
    { kanji: '大学', meaning: 'university', romaji: 'daigaku' },
    { kanji: '大丈夫', meaning: 'safe, all right, okay', romaji: 'daijoubu' },
  ];