export const n5Part3 = [
    { kanji: '本棚', meaning: 'bookshelf, bookcase', romaji: 'hondana' },
    { kanji: '本当', meaning: 'truth, reality', romaji: 'hontou' },
    { kanji: '他', meaning: 'other, the rest', romaji: 'hoka' },
    { kanji: '百', meaning: 'hundred', romaji: 'hyaku' },
    { kanji: '一', meaning: 'one', romaji: 'ichi' },
    { kanji: '一番', meaning: 'number one, first, first place', romaji: 'ichiban' },
    { kanji: '一日', meaning: 'one day', romaji: 'ichinichi' },
    { kanji: '家', meaning: 'house, residence', romaji: 'ie' },
    { kanji: 'いい', meaning: 'good', romaji: 'ii' },
    { kanji: '否', meaning: 'no, nay', romaji: 'iie' },
    { kanji: '池', meaning: 'pond', romaji: 'ike' },
    { kanji: '行く', meaning: 'to go', romaji: 'iku' },
    { kanji: '幾ら', meaning: 'how much, how many', romaji: 'ikura' },
    { kanji: '幾つ', meaning: 'how many, how old', romaji: 'ikutsu' },
    { kanji: '今', meaning: 'now, the present time', romaji: 'ima' },
    { kanji: '意味', meaning: 'meaning, significance', romaji: 'imi' },
    { kanji: '妹', meaning: 'younger sister', romaji: 'imouto' },
    { kanji: '犬', meaning: 'dog', romaji: 'inu' },
    { kanji: '入れる', meaning: 'to put in, to let in', romaji: 'ireru' },
    { kanji: '入口', meaning: 'entrance, gate', romaji: 'iriguchi' },
    { kanji: '色', meaning: 'color, complexion', romaji: 'iro' },
    { kanji: '色々', meaning: 'various', romaji: 'iroiro' },
    { kanji: '要る', meaning: 'to need, to want', romaji: 'iru' },
    { kanji: '医者', meaning: '(medical) doctor, physician', romaji: 'isha' },
    { kanji: '忙しい', meaning: 'busy, occupied', romaji: 'isogashii' },
    { kanji: '一緒', meaning: 'together', romaji: 'issho' },
    { kanji: '椅子', meaning: 'chair, stool', romaji: 'isu' },
    { kanji: '痛い', meaning: 'painful, sore', romaji: 'itai' },
    { kanji: '五日', meaning: 'fifth day of the month, five days', romaji: 'itsuka' },
    { kanji: 'いつも', meaning: 'always, usually', romaji: 'itsumo' },
    { kanji: '五つ', meaning: 'five', romaji: 'itsutsu' },
    { kanji: '言う', meaning: 'to say, to utter', romaji: 'iu' },
    { kanji: '嫌', meaning: 'disagreeable, detestable', romaji: 'iya' },
    { kanji: '字引', meaning: 'dictionary', romaji: 'jibiki' },
    { kanji: '自分', meaning: 'myself, yourself, oneself', romaji: 'jibun' },
    { kanji: '自動車', meaning: 'automobile', romaji: 'jidousha' },
    { kanji: '時間', meaning: 'time, hours', romaji: 'jikan' },
    { kanji: '辞書', meaning: 'dictionary', romaji: 'jisho' },
    { kanji: '自転車', meaning: 'bicycle', romaji: 'jitensha' },
    { kanji: '上手', meaning: 'skill, skillful', romaji: 'jouzu' },
    { kanji: '授業', meaning: 'lesson, class work', romaji: 'jugyou' },
    { kanji: '鞄', meaning: 'bag', romaji: 'kaban' },
    { kanji: '花瓶', meaning: '(flower) vase', romaji: 'kabin' },
    { kanji: '角', meaning: 'corner, edge', romaji: 'kado' },
    { kanji: '帰る', meaning: 'to return, to come home', romaji: 'kaeru' },
    { kanji: '返す', meaning: 'to return (something)', romaji: 'kaesu' },
    { kanji: '鍵', meaning: 'key, lock', romaji: 'kagi' },
    { kanji: '階段', meaning: 'stairs, stairway', romaji: 'kaidan' },
    { kanji: '買物', meaning: 'shopping', romaji: 'kaimono' },
    { kanji: '会社', meaning: 'company, corporation', romaji: 'kaisha' },
    { kanji: '書く', meaning: 'to write, to compose', romaji: 'kaku' },
    { kanji: '紙', meaning: 'paper', romaji: 'kami' },
    { kanji: '漢字', meaning: 'Chinese characters', romaji: 'kanji' },
    { kanji: '体', meaning: 'body, torso', romaji: 'karada' },
    { kanji: '辛い', meaning: 'spicy, hot', romaji: 'karai' },
    { kanji: '借りる', meaning: 'to borrow', romaji: 'kariru' },
    { kanji: '軽い', meaning: 'light (not heavy)', romaji: 'karui' },
    { kanji: '傘', meaning: 'umbrella', romaji: 'kasa' },
    { kanji: '貸す', meaning: 'to lend, to loan', romaji: 'kasu' },
    { kanji: '方', meaning: 'person', romaji: 'kata' },
    { kanji: '家庭', meaning: 'home, family, household', romaji: 'katei' },
    { kanji: '買う', meaning: 'to buy, to purchase', romaji: 'kau' },
    { kanji: '可愛い', meaning: 'cute, adorable', romaji: 'kawaii' },
    { kanji: '家族', meaning: 'family, members of a family', romaji: 'kazoku' },
    { kanji: '風', meaning: 'wind, breeze', romaji: 'kaze' },
    { kanji: '風邪', meaning: 'cold, influenza', romaji: 'kaze' },
    { kanji: '川', meaning: 'river, stream', romaji: 'kawa' },
    { kanji: '警官', meaning: 'police officer, policeman', romaji: 'keikan' },
    { kanji: '結婚', meaning: 'marriage', romaji: 'kekkon' },
    { kanji: '結構', meaning: 'splendid, nice, okay', romaji: 'kekkou' },
    { kanji: '今朝', meaning: 'this morning', romaji: 'kesa' },
    { kanji: '消す', meaning: 'to erase, to delete', romaji: 'kesu' },
    { kanji: '木', meaning: 'tree', romaji: 'ki' },
    { kanji: '消える', meaning: 'to go out, to vanish', romaji: 'kieru' },
    { kanji: '黄色い', meaning: 'yellow', romaji: 'kiiroi' },
    { kanji: '昨日', meaning: 'yesterday', romaji: 'kinou' },
    { kanji: '金曜日', meaning: 'Friday', romaji: 'kin’youbi' },
    { kanji: '切符', meaning: 'ticket', romaji: 'kippu' },
    { kanji: '嫌い', meaning: 'dislike, hate', romaji: 'kirai' },
    { kanji: '切る', meaning: 'to cut', romaji: 'kiru' },
    { kanji: '着る', meaning: 'to wear, to put on', romaji: 'kiru' },
    { kanji: '喫茶店', meaning: 'coffee shop', romaji: 'kissaten' },
    { kanji: '北', meaning: 'north', romaji: 'kita' },
    { kanji: '汚い', meaning: 'dirty, filthy', romaji: 'kitanai' },
    { kanji: '切手', meaning: 'stamp (postage)', romaji: 'kitte' },
    { kanji: '九', meaning: 'nine', romaji: 'kyuu' },
    { kanji: '声', meaning: 'voice', romaji: 'koe' },
    { kanji: 'ここ', meaning: 'here', romaji: 'koko' },
    { kanji: '九日', meaning: 'ninth day of the month, nine days', romaji: 'kokonoka' },
    { kanji: '困る', meaning: 'to be troubled, to be worried', romaji: 'komaru' },
    { kanji: '今晩', meaning: 'tonight, this evening', romaji: 'konban' },
    { kanji: '今週', meaning: 'this week', romaji: 'konshuu' },    
  ];