export const n5Part2 = [
    { kanji: '段々', meaning: 'gradually, little by little', romaji: 'dandan' },
    { kanji: '誰', meaning: 'who', romaji: 'dare' },
    { kanji: '誰か', meaning: 'someone, somebody', romaji: 'dareka' },
    { kanji: '出す', meaning: 'to take out', romaji: 'dasu' },
    { kanji: '出口', meaning: 'exit, gateway', romaji: 'deguchi' },
    { kanji: '出かける', meaning: 'to go out', romaji: 'dekakeru' },
    { kanji: '電気', meaning: 'electricity, light', romaji: 'denki' },
    { kanji: '電車', meaning: 'train, electric train', romaji: 'densha' },
    { kanji: '電話', meaning: 'telephone call, phone', romaji: 'denwa' },
    { kanji: '出る', meaning: 'to leave, to exit', romaji: 'deru' },
    { kanji: 'どちら', meaning: 'which one', romaji: 'dochira' },
    { kanji: 'どこ', meaning: 'where', romaji: 'doko' },
    { kanji: 'どう', meaning: 'how, in what way, how about', romaji: 'dou' },
    { kanji: '動物', meaning: 'animal', romaji: 'doubutsu' },
    { kanji: 'どうも', meaning: 'thanks', romaji: 'doumo' },
    { kanji: 'どうして', meaning: 'why, for what reason', romaji: 'doushite' },
    { kanji: 'どうぞ', meaning: 'please, feel free', romaji: 'douzo' },
    { kanji: '土曜日', meaning: 'Saturday', romaji: 'doyoubi' },
    { kanji: '絵', meaning: 'picture, drawing, painting', romaji: 'e' },
    { kanji: '映画', meaning: 'movie, film', romaji: 'eiga' },
    { kanji: '映画館', meaning: 'movie theater, cinema', romaji: 'eigakan' },
    { kanji: '英語', meaning: 'English (language)', romaji: 'eigo' },
    { kanji: '駅', meaning: 'station', romaji: 'eki' },
    { kanji: '鉛筆', meaning: 'pencil', romaji: 'enpitsu' },
    { kanji: '服', meaning: 'clothes', romaji: 'fuku' },
    { kanji: '吹く', meaning: 'to blow (wind)', romaji: 'fuku' },
    { kanji: '二人', meaning: 'two people, pair', romaji: 'futari' },
    { kanji: '二日', meaning: 'second day of the month, two days', romaji: 'futsuka' },
    { kanji: '降る', meaning: 'to fall (rain)', romaji: 'furu' },
    { kanji: '古い', meaning: 'old (not person)', romaji: 'furui' },
    { kanji: '封筒', meaning: 'envelope', romaji: 'fuutou' },
    { kanji: '冬', meaning: 'winter', romaji: 'fuyu' },
    { kanji: '学校', meaning: 'school', romaji: 'gakkou' },
    { kanji: '学生', meaning: 'student', romaji: 'gakusei' },
    { kanji: '外国', meaning: 'foreign country', romaji: 'gaikoku' },
    { kanji: '外国人', meaning: 'foreigner', romaji: 'gaikokujin' },
    { kanji: '元気', meaning: 'lively, full of spirit', romaji: 'genki' },
    { kanji: '玄関', meaning: 'entranceway, entrance hall', romaji: 'genkan' },
    { kanji: '月曜日', meaning: 'Monday', romaji: 'getsuyoubi' },
    { kanji: '銀行', meaning: 'bank', romaji: 'ginkou' },
    { kanji: '牛肉', meaning: 'beef', romaji: 'gyuuniku' },
    { kanji: '牛乳', meaning: 'milk', romaji: 'gyuunyuu' },
    { kanji: '五', meaning: 'five', romaji: 'go' },
    { kanji: '午後', meaning: 'afternoon, p.m.', romaji: 'gogo' },
    { kanji: 'ご飯', meaning: 'cooked rice, meal', romaji: 'gohan' },
    { kanji: '午前', meaning: 'morning, a.m.', romaji: 'gozen' },
    { kanji: '歯', meaning: 'tooth', romaji: 'ha' },
    { kanji: '八', meaning: 'eight | hachi' },
    { kanji: '葉書', meaning: 'postcard', romaji: 'hagaki' },
    { kanji: '母', meaning: 'mother', romaji: 'haha' },
    { kanji: '入る', meaning: 'to enter, to go into', romaji: 'hairu' },
    { kanji: '灰皿', meaning: 'ashtray', romaji: 'haizara' },
    { kanji: '始め', meaning: 'beginning, start', romaji: 'hajime' },
    { kanji: '初めて', meaning: 'for the first time', romaji: 'hajimete' },
    { kanji: '始まる', meaning: 'to begin, to start', romaji: 'hajimaru' },
    { kanji: '箱', meaning: 'box, chest', romaji: 'hako' },
    { kanji: '半分', meaning: 'half', romaji: 'hanbun' },
    { kanji: '花', meaning: 'flower, blossom', romaji: 'hana' },
    { kanji: '鼻', meaning: 'nose', romaji: 'hana' },
    { kanji: '話', meaning: 'talk, speech, chat', romaji: 'hanashi' },
    { kanji: '話す', meaning: 'to talk, to speak', romaji: 'hanasu' },
    { kanji: '晴れる', meaning: 'to clear up', romaji: 'hareru' },
    { kanji: '春', meaning: 'spring, springtime', romaji: 'haru' },
    { kanji: '貼る', meaning: 'to stick, to paste', romaji: 'haru' },
    { kanji: '箸', meaning: 'chopsticks', romaji: 'hashi' },
    { kanji: '橋', meaning: 'bridge', romaji: 'hashi' },
    { kanji: '走る', meaning: 'to run', romaji: 'hashiru' },
    { kanji: '二十歳', meaning: 'twenty years old', romaji: 'hatachi' },
    { kanji: '働く', meaning: 'to work', romaji: 'hataraku' },
    { kanji: '二十日', meaning: 'twentieth day of the month, twenty days', romaji: 'hatsuka' },
    { kanji: '早い', meaning: 'early', romaji: 'hayai' },
    { kanji: '早く', meaning: 'early, soon, quickly', romaji: 'hayaku' },
    { kanji: '速い', meaning: 'fast, quick', romaji: 'hayai' },
    { kanji: '辺', meaning: 'area, vicinity', romaji: 'hen' },
    { kanji: '下手', meaning: 'unskillful', romaji: 'heta' },
    { kanji: '部屋', meaning: 'room, chamber', romaji: 'heya' },
    { kanji: '日', meaning: 'day, sun', romaji: 'hi' },
    { kanji: '火', meaning: 'fire, flame', romaji: 'hi' },
    { kanji: '左', meaning: 'left, left hand side', romaji: 'hidari' },
    { kanji: '東', meaning: 'east', romaji: 'higashi' },
    { kanji: '弾く', meaning: 'to play (piano, guitar)', romaji: 'hiku' },
    { kanji: '引く', meaning: 'to pull, to draw', romaji: 'hiku' },
    { kanji: '低い', meaning: 'low (rank), short (height)', romaji: 'hikui' },
    { kanji: '飛行機', meaning: 'aeroplane, airplane', romaji: 'hikouki' },
    { kanji: '暇', meaning: 'spare time, free time', romaji: 'hima' },
    { kanji: '広い', meaning: 'spacious, vast, wide', romaji: 'hiroi' },
    { kanji: '昼', meaning: 'noon, midday', romaji: 'hiru' },
    { kanji: '昼ご飯', meaning: 'lunch, midday meal', romaji: 'hirugohan' },
    { kanji: '人', meaning: 'person', romaji: 'hito' },
    { kanji: '一人', meaning: 'one person, alone', romaji: 'hitori' },
    { kanji: '一つ', meaning: 'one', romaji: 'hitotsu' },
    { kanji: '本', meaning: 'book', romaji: 'hon' },    
  ];