export const n5Part5 = [
    { kanji: '覚える', meaning: 'to memorize, to remember', romaji: 'oboeru' },
    { kanji: 'お茶', meaning: 'tea', romaji: 'ocha' },
    { kanji: 'お風呂', meaning: 'bath', romaji: 'ofuro' },
    { kanji: '美味しい', meaning: 'delicious, tasty', romaji: 'oishii' },
    { kanji: 'お母さん', meaning: 'mother', romaji: 'okaasan' },
    { kanji: 'お金', meaning: 'money', romaji: 'okane' },
    { kanji: 'お菓子', meaning: 'sweets, candy', romaji: 'okashi' },
    { kanji: '起きる', meaning: 'to get up, to rise', romaji: 'okiru' },
    { kanji: '置く', meaning: 'to put, to place', romaji: 'oku' },
    { kanji: '奥さん', meaning: 'wife, your wife, his wife', romaji: 'okusan' },
    { kanji: 'お巡りさん', meaning: 'police officer', romaji: 'omawarisan' },
    { kanji: '重い', meaning: 'heavy, weighty', romaji: 'omoi' },
    { kanji: '面白い', meaning: 'interesting, fascinating', romaji: 'omoshiroi' },
    { kanji: 'お腹', meaning: 'stomach', romaji: 'onaka' },
    { kanji: '音楽', meaning: 'music', romaji: 'ongaku' },
    { kanji: '女', meaning: 'female, woman', romaji: 'onna' },
    { kanji: '同じ', meaning: 'same, identical', romaji: 'onaji' },
    { kanji: 'お姉さん', meaning: 'elder sister', romaji: 'oneesan' },
    { kanji: 'お兄さん', meaning: 'elder brother', romaji: 'oniisan' },
    { kanji: '女の子', meaning: 'girl', romaji: 'onna no ko' },
    { kanji: '多い', meaning: 'many, numerous, a lot', romaji: 'ooi' },
    { kanji: '大きい', meaning: 'big, large, great', romaji: 'ookii' },
    { kanji: '大勢', meaning: 'many, crowd, great number of people', romaji: 'oozei' },
    { kanji: '降りる', meaning: 'to descend, to get off', romaji: 'oriru' },
    { kanji: 'お皿', meaning: 'plate, dish', romaji: 'osara' },
    { kanji: '教える', meaning: 'to teach, to instruct', romaji: 'oshieru' },
    { kanji: '遅い', meaning: 'slow, late', romaji: 'osoi' },
    { kanji: '押す', meaning: 'to push, to press', romaji: 'osu' },
    { kanji: 'お手洗い', meaning: 'toilet, restroom', romaji: 'otearai' },
    { kanji: '男', meaning: 'man, male', romaji: 'otoko' },
    { kanji: '男の子', meaning: 'boy', romaji: 'otoko no ko' },
    { kanji: '大人', meaning: 'adult', romaji: 'otona' },
    { kanji: '一昨日', meaning: 'day before yesterday', romaji: 'ototoi' },
    { kanji: 'お父さん', meaning: 'father, dad', romaji: 'otousan' },
    { kanji: '一昨年', meaning: 'year before last', romaji: 'ototoshi' },
    { kanji: '弟', meaning: 'younger brother', romaji: 'otouto' },
    { kanji: '終わる', meaning: 'to finish, to end', romaji: 'owaru' },
    { kanji: '泳ぐ', meaning: 'to swim', romaji: 'oyogu' },
    { kanji: '来月', meaning: 'next month', romaji: 'raigetsu' },
    { kanji: '来年', meaning: 'next year', romaji: 'rainen' },
    { kanji: '来週', meaning: 'next week', romaji: 'raishuu' },
    { kanji: '冷蔵庫', meaning: 'refrigerator', romaji: 'reizouko' },
    { kanji: '練習', meaning: 'practice', romaji: 'renshuu' },
    { kanji: '六', meaning: 'six', romaji: 'roku' },
    { kanji: '廊下', meaning: 'corridor, hallway', romaji: 'rouka' },
    { kanji: '旅行', meaning: 'travel, trip', romaji: 'ryokou' },
    { kanji: '料理', meaning: 'cooking, cuisine', romaji: 'ryouri' },
    { kanji: '両親', meaning: 'parents, both parents', romaji: 'ryoushin' },
    { kanji: '留学生', meaning: 'overseas student', romaji: 'ryuugakusei' },
    { kanji: '歳', meaning: 'years old', romaji: 'sai' },
    { kanji: '財布', meaning: 'purse, wallet', romaji: 'saifu' },
    { kanji: '魚', meaning: 'fish', romaji: 'sakana' },
    { kanji: '酒', meaning: 'alcohol, sake', romaji: 'sake' },
    { kanji: '先', meaning: 'previous, prior, former', romaji: 'saki' },
    { kanji: '咲く', meaning: 'to bloom', romaji: 'saku' },
    { kanji: '作文', meaning: 'writing (an essay), composition', romaji: 'sakubun' },
    { kanji: '寒い', meaning: 'cold', romaji: 'samui' },
    { kanji: '三', meaning: 'three', romaji: 'san' },
    { kanji: '散歩', meaning: 'walk, stroll', romaji: 'sanpo' },
    { kanji: '再来年', meaning: 'year after next', romaji: 'sarainen' },
    { kanji: '砂糖', meaning: 'sugar', romaji: 'satou' },
    { kanji: '背', meaning: 'height, stature', romaji: 'se' },
    { kanji: '背広', meaning: 'business suit', romaji: 'sebiro' },
    { kanji: '生徒', meaning: 'pupil', romaji: 'seito' },
    { kanji: '石鹸', meaning: 'soap', romaji: 'sekken' },
    { kanji: '狭い', meaning: 'narrow, confined', romaji: 'semai' },
    { kanji: '千', meaning: 'thousand', romaji: 'sen' },
    { kanji: '先月', meaning: 'last month', romaji: 'sengetsu' },
    { kanji: '先生', meaning: 'teacher, master, doctor', romaji: 'sensei' },
    { kanji: '先週', meaning: 'last week', romaji: 'senshuu' },
    { kanji: '洗濯', meaning: 'washing, laundry', romaji: 'sentaku' },
    { kanji: '四', meaning: 'four', romaji: 'shi' },
    { kanji: '七', meaning: 'seven', romaji: 'shichi' },
    { kanji: '写真', meaning: 'photograph, photo, picture', romaji: 'shashin' },
    { kanji: '仕事', meaning: 'work, job', romaji: 'shigoto' },
    { kanji: '閉まる', meaning: 'to be shut, to close', romaji: 'shimaru' },
    { kanji: '閉める', meaning: 'to close, to shut', romaji: 'shimeru' },
    { kanji: '締める', meaning: 'to tie, to fasten', romaji: 'shimeru' },
    { kanji: '新聞', meaning: 'newspaper', romaji: 'shinbun' },
    { kanji: '死ぬ', meaning: 'to die, to pass away', romaji: 'shinu' },
    { kanji: '塩', meaning: 'salt', romaji: 'shio' },
    { kanji: '白い', meaning: 'white', romaji: 'shiroi' },
    { kanji: '知る', meaning: 'to be aware of, to know', romaji: 'shiru' },
    { kanji: '下', meaning: 'below, down, under', romaji: 'shita' },
    { kanji: '質問', meaning: 'question, inquiry', romaji: 'shitsumon' },
    { kanji: '静か', meaning: 'quiet, silent', romaji: 'shizuka' },
    { kanji: '食堂', meaning: 'dining room, dining hall', romaji: 'shokudou' },
    { kanji: '醤油', meaning: 'soy sauce', romaji: 'shouyu' },
    { kanji: '宿題', meaning: 'homework', romaji: 'shukudai' },
    { kanji: '側', meaning: 'near, close, beside', romaji: 'soba' },
    { kanji: '空', meaning: 'sky', romaji: 'sora' },
    { kanji: '外', meaning: 'outside, exterior', romaji: 'soto' },    
  ];